[package]
name = "rssflow"
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
opt-level = 3
lto = "fat"
strip = true

[profile.dev.package.sqlx-macros]
opt-level = 3

[features]
default = ["filter", "retrieve", "sanitise", "sha1"]
filter = ["dep:regex", "dep:serde_regex"]
retrieve = ["dep:scraper"]
sanitise = ["dep:ammonia"]
wasm = ["dep:wasmtime", "dep:wasmtime-wasi"]
sha1 = ["dep:sha1"]

[dependencies]
axum = { version = "0.7", features = ["macros"] }
url = { version = "2.5", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["charset", "http2", "rustls-tls"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "chrono"] }
bytes = { version = "1.6", features = ["serde"] }

chrono = "0.4"
hmac = "0.12"
sha2 = "0.10"
sha1 = { version = "0.10", optional = true }
rand = "0.8"
hex = "0.4.3"

#rss = { version = "2", features = ["url", "with-serde", "atom"] }
atom_syndication = { version = "0.12", features = ["with-serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["rt-multi-thread"] }
async-trait = "0.1"
futures = "0.3"
mimalloc = "0.1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"

uuid = { version = "1.9.1", features = ["serde", "v7"] }
strum = { version = "0.26", features = ["derive"] }
derive_more = "0.99"
parking_lot = "0.12"
confique = { version = "0.2", default-features = false, features = ["toml"] }


ammonia = { version = "4.0", optional = true }
regex = { version = "1.10", optional = true }
scraper = { version = "0.19", optional = true, git = "https://github.com/causal-agent/scraper.git" }
serde_regex = { version = "1", optional = true }
wasmtime = { version = "22", optional = true }
wasmtime-wasi = { version = "22", optional = true }
