[package]
name = "rss-pipe"
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
opt-level = 3
lto = "fat"

[features]
default = ["filter", "retrieve", "sanitise", "wasm"]
filter = ["dep:regex", "dep:serde_regex"]
retrieve = ["dep:scraper"]
sanitise = ["dep:ammonia"]
wasm = ["dep:wasmtime", "dep:wasmtime-wasi"]



[dependencies]
anyhow = "1"
async-trait = "0.1"

axum = { version = "0.7", features = ["macros"] }
bytes = "1.6"
futures = "0.3"
mimalloc = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["charset", "http2", "rustls-tls"] }
rss = { version = "2", features = ["url", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
#typetag = "0.2.16"
url = { version = "2.5", features = ["serde"] }

ammonia = { version = "4.0", optional = true }
regex = { version = "1.10", optional = true }
scraper = { version = "0.19", optional = true }
serde_regex = { version = "1", optional = true }
wasmtime = { version = "22", optional = true }
wasmtime-wasi = { version = "22", optional = true }
